version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: devsaround-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: devsaround
    volumes:
      - mongodb_data:/data/db
    networks:
      - devsaround-network

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: devsaround-api
    restart: always
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/devsaround?authSource=admin
    depends_on:
      - mongodb
    networks:
      - devsaround-network
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: devsaround-web
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    depends_on:
      - api
    networks:
      - devsaround-network
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
      - /app/apps/web/.next

volumes:
  mongodb_data:
    driver: local

networks:
  devsaround-network:
    driver: bridge