export const ENV = {
  NEXT_PUBLIC_BASE_SERVER_API: process.env.NEXT_PUBLIC_BASE_SERVER_API,
  NEXT_PUBLIC_FILE_UPLOAD_API_KEY: process.env.NEXT_PUBLIC_FILE_UPLOAD_API_KEY,
  NEXT_PUBLIC_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_PUBLIC_SITE_URL,
} as const;
